<% host_url = ENV['HOST_URL'].presence || "https://#{ENV['HEROKU_APP_NAME']}.herokuapp.com/" %>
default: &default
  app:
    url: <%= uri = URI.parse(host_url); uri.path = ''; uri %>
    host: <%= URI.parse(host_url).host %>
    port: <%= URI.parse(host_url).port %>
    secret_key: <%= ENV['SECRET_KEY'] %>
    pepper: <%= ENV['PEPPER'] %>
  mailer:
    default_sender: <%= ENV['MAILER_DEFAULT_SENDER'] %>
  aws_s3:
    access_key_id: <%= ENV['AWS_S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_S3_SECRET_ACCESS_KEY'] %>
    region: <%= ENV['AWS_S3_REGION'] %>
    bucket: <%= ENV['AWS_S3_BUCKET'] %>
    asset_host: <%= ENV['AWS_S3_ASSET_HOST'] %>
  facebook:
    app_id: <%= ENV['FB_APP_ID'] %>
    app_secret: <%= ENV['FB_APP_SECRET'] %>
  new_relic:
    license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  feature_flags:
    show_book_info_requires_sign_in: <%= ENV['FF_SHOW_BOOK_INFO_REQUIRES_SIGN_IN'] == 'true' %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
